---
namespace: jvzantvoort
name: home
version: 1.0.1
readme: README.md
authors:
  - John van Zantvoort <john@vanzantvoort.org>
description: Ansible collection for personal use
license:
  - GPL-2.0-or-later
tags: []
dependencies: {}
repository: https://github.com/jvzantvoort/ansible-collection-jvzantvoort-home
documentation: https://github.com/jvzantvoort/ansible-collection-jvzantvoort-home/wiki
homepage: https://github.com/jvzantvoort/ansible-collection-jvzantvoort-home/wiki
issues: https://github.com/jvzantvoort/ansible-collection-jvzantvoort-home/issues
build_ignore: []
