---
- name: Write the service file
  ansible.builtin.template:
    src: "etc/systemd/system/gotify.service.j2"
    dest: "/etc/systemd/system/gotify.service"
    owner: "root"
    group: "root"
    mode: '0644'
  register: writeservice
  notify: Restart gotify service

- name: Re-load systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: writeservice.changed

...
