---
gotify_version: "2.6.3"
gotify_goarch: "amd64"
gotify_goos: "linux"
gotify_download_url: "https://github.com/gotify/server/releases/download/v{{ gotify_version }}/gotify-{{ gotify_goos }}-{{ gotify_goarch }}.zip"
gotify_dl_bin_name: "gotify-{{ gotify_goos }}-{{ gotify_goarch }}"
gotify_dest_versioned: "/usr/local/bin/gotify-{{ gotify_version }}"
gotify_dest: "/usr/local/bin/gotify"

gotify_username: "gotify"
gotify_groupname: "gotify"
gotify_comment: ""
gotify_home: "/home/{{ gotify_username }}"

# config vars
gotify_server_port: 7070
gotify_server_keepaliveperiodseconds: 0
gotify_server_listenaddr: ""

# database
gotify_database_admin_username: ""
gotify_database_admin_password: ""
gotify_database_host: "localhost"
gotify_database_port: 3306
gotify_database_dialect: "mysql"
gotify_database_username: "gotify"
gotify_database_password: "gotify"
gotify_database_name: "gotify"  # database name

gotify_database_connection: "{{ gotify_database_username }}:{{ gotify_database_password }}@tcp(localhost:3306)/{{ gotify_database_name }}?charset=utf8&parseTime=True&loc=Local"

# app user

gotify_defaultuser_name: "admin"
gotify_defaultuser_pass: "admin"

gotify_passstrength: 10                # the bcrypt password strength (higher = better but also slower)
gotify_uploadedimagesdir: data/images  # the directory for storing uploaded images
gotify_pluginsdir: data/plugins        # the directory where plugin resides
gotify_registration: false             # enable registrations
